### ISSUE TITLE
issueベースの開発 レビュー

### ISSUE THREAD

**Issue by Kazuya-53b** [Kazuya-53b/NyanDex#44]
■Webアプリの概要
NyanDexは猫好きに癒しを与えるプロフィール図鑑アプリ
自身の猫を登録、登録された他のユーザーの様々な猫を見ることができる
詳細検索で様々な猫を検索することが可能

■1週間辺りの開発に向けられる時間
- 1週間あたり：40～50時間（20～25ポイント）

■ProjectsのURL
https://github.com/users/Kazuya-53b/projects/2

■MVPリリースまで
- [ ] rails new
- [ ] Herokuにデプロイ
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] パスワード変更機能
- [ ] メールアドレス変更機能
- [ ] ユーザー情報登録機能
- [ ] ユーザー情報変更機能
- [ ] 猫プロフィール登録機能
- [ ] 猫プロフィール編集機能
- [ ] 詳細検索機能
- [ ] 独自ドメイン

■MVP後
- [ ] ブックマーク機能
- [ ] オートコンプリート検索
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] パスワードリセット機能
- [ ] RSpec（モデルテスト・システムテスト）
- [ ] CI（GitHubActions）
- [ ] ファビコン
- [ ] レスポンシブ対応

■MVPレビュー依頼予定日
予定日：2024年 10月 11日

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。
ストーリーポイントを確認したところ、4ポイント以上のカードが存在するのを確認しました。（環境セットアップ）
カリキュラムにもありましたとおり、ストーリーポイント3以下になるように細かくissue化してください。
細かくissue化することで、不明瞭な箇所、明瞭な箇所が可視化されることに加えて、進捗を感じられながら開発を進めることができます。
対応の上、再提出操作をお願いいたします。

**Comment by Kazuya-53b** [comment]
ご指摘のissueをHotwire、TailswindCSS、DaisyUIの３つのセットアップに細分化いたしました。
再レビューよろしくお願いいたします。

**Comment by Kazuya-53b** [comment]
> 対応ありがとうございます。 ストーリーポイントを確認したところ、4ポイント以上のカードが存在するのを確認しました。（環境セットアップ） カリキュラムにもありましたとおり、ストーリーポイント3以下になるように細かくissue化してください。 細かくissue化することで、不明瞭な箇所、明瞭な箇所が可視化されることに加えて、進捗を感じられながら開発を進めることができます。 対応の上、再提出操作をお願いいたします。

**Comment by Kazuya-53b** [comment]
ご指摘のissueをHotwire、TailswindCSS、DaisyUIの３つのセットアップに細分化いたしました。
再レビューよろしくお願いいたします。

**Comment by beppumasaki** [comment]
概ね良いかと思います。LGTMです。
